# Site settings
title: ITNotes
description: "Кратко об IT"
  
baseurl: ""
url: "https://itnotes.github.io"
port: 8080
host: 0.0.0.0

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
paginate: 5
paginate_path: page:num
contacts:
  twitter: itnotes_io
  github: itnotes
keywords:
  - java
  - kotlin
  - maven
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist